### ISSUE TITLE
Arduino Micro Compilation Error

### ISSUE THREAD

**Issue by jamesleipold** [Legion2/CorsairLightingProtocolBoards#4]
Compiling for Arduino Micro produces the following error code:

Arduino: 1.8.11 (Windows 10), Board: "CLP SparkFun Pro Micro 5V, 16 MHz, Lighting Node CORE"
```
C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\james\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\james\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\james\Google Drive\Projects\Arduino\libraries -fqbn=Legion2:avr:promicro5vclp:device=lnc -ide-version=10811 -build-path C:\Users\james\AppData\Local\Temp\arduino_build_673371 -warnings=none -build-cache C:\Users\james\AppData\Local\Temp\arduino_cache_185092 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avr-gcc-4.8.1-arduino5.path=C:\Users\james\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino5 -prefs=runtime.tools.avrdude.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude-6.0.1-arduino5.path=C:\Users\james\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.0.1-arduino5 -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino5.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude-6.3.0-arduino17.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA-1.3.0.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -verbose C:\Users\james\Google Drive\Projects\Arduino\libraries\CorsairLightingProtocol-dev\examples\LightingNodePRO\LightingNodePRO.ino
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x83358a]

goroutine 1 [running]:
github.com/arduino/arduino-cli/legacy/builder.(*SetupBuildProperties).Run(0xf47308, 0x120ce5a0, 0xf47308, 0x123a64c0)
	/home/jenkins/workspace/arduino-builder-all-cross-cli-inception/src/github.com/arduino/arduino-cli/legacy/builder/setup_build_properties.go:79 +0xd6a
github.com/arduino/arduino-cli/legacy/builder.(*ContainerSetupHardwareToolsLibsSketchAndProps).Run(0xf47308, 0x120ce5a0, 0xf47308, 0x1202e000)
	/home/jenkins/workspace/arduino-builder-all-cross-cli-inception/src/github.com/arduino/arduino-cli/legacy/builder/container_setup.go:85 +0x408
github.com/arduino/arduino-cli/legacy/builder.runCommands(0x120ce5a0, 0x1203df0c, 0x2, 0x2, 0x1, 0xa43e08, 0x70c7ad)
	/home/jenkins/workspace/arduino-builder-all-cross-cli-inception/src/github.com/arduino/arduino-cli/legacy/builder/builder.go:195 +0xbd
github.com/arduino/arduino-cli/legacy/builder.(*ParseHardwareAndDumpBuildProperties).Run(0x12065f40, 0x120ce5a0, 0xf47254, 0x120073a0)
	/home/jenkins/workspace/arduino-builder-all-cross-cli-inception/src/github.com/arduino/arduino-cli/legacy/builder/builder.go:183 +0xbc
github.com/arduino/arduino-cli/legacy/builder.RunParseHardwareAndDumpBuildProperties(...)
	/home/jenkins/workspace/arduino-builder-all-cross-cli-inception/src/github.com/arduino/arduino-cli/legacy/builder/builder.go:216
main.main()
	/home/jenkins/workspace/arduino-builder-all-cross-cli-inception/src/github.com/arduino/arduino-builder/main.go:389 +0x710
C:\Program Files (x86)\Arduino\arduino-builder returned 2

Error compiling for board CLP SparkFun Pro Micro 5V, 16 MHz.
```

**Comment by Legion2** [comment]
You use the dev version of the "Corsair Lighting Protocol" library (you installed the zip or cloned it) and the release version (installed with library manager) at the same time. Please only use one version of the library and remove the other.
Same error as Legion2/CorsairLightingProtocol#73.

**Comment by jamesleipold** [comment]
Sorry - didn't mean to close.

I still get the same issue after deleting the library (there was only the dev version installed) and adding the master version. 
![image](https://user-images.githubusercontent.com/41983227/73592748-64cf1700-4538-11ea-83d1-7cdb578151ee.png)

**Comment by Legion2** [comment]
https://github.com/sparkfun/Arduino_Boards#installation-instructions you need to install the SparkFun Boards

![](https://media.discordapp.net/attachments/668232874239197217/668234601336143872/unknown.png)
